### ISSUE TITLE
Missing support for VidyoClient SDK 21.6.0.7

### ISSUE THREAD

**Issue by jmosbech** [Vidyo/VidyoPlatform-Connector-Xamarin#2]
Hello Vidyo,

The application crashes with the following error when trying to use VidyoClient SDK 21.6.0.7 on Android.

> JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception java.lang.NoSuchMethodError: no static method "Lcom/vidyo/VidyoClient/Connector/ConnectorPkg;.setApplicationUIContext(Landroid/app/Activity;)V"

We would like to upgrade to the latest SDK, but this is blocking us. How can we work around this issue?

The full crash log is attached in case it's relevant: [VidyoConnector-log-2021-12-10.txt](https://github.com/Vidyo/VidyoPlatform-Connector-Xamarin/files/7691887/VidyoConnector-log-2021-12-10.txt)

**Comment by jmosbech** [comment]
This bug is still present in 21.6.1.1. 

Apparently the last working version is 21.5.0.13.

Any updates @tmelko-vidyo @vova-eh-vidyo?

**Comment by jmosbech** [comment]
This bug is still present in 21.6.1.1. 

Apparently the last working version is 21.5.0.13.

Any updates @tmelko-vidyo @vova-eh-vidyo?

**Comment by vova-eh-vidyo** [comment]
@tmelko-vidyo , could you please look into this when you're back?
@jmosbech , please expect an update early next week.

**Comment by tmelko-vidyo** [comment]
@jmosbech 
This issue will be resolved with the 22.x version within C# binding.

Apparently, you can manually correct C# binding files, add Kotlin Plugin and comply with 21.6.x version:

1. **ConnectorPKG.cs**
 Correct ANDROID block in the bottom with this:
 `#if __ANDROID__#if __ANDROID__ internal static IntPtr javaClassHandle; internal static IntPtr javaClassRef; static IntPtr javaMethodRef; public static void SetApplicationUIContext(Context context) { javaClassRef = Android.Runtime.JNIEnv.FindClass("com/vidyo/VidyoClient/Connector/ConnectorPkg", ref javaClassHandle); javaMethodRef = Android.Runtime.JNIEnv.GetStaticMethodID(javaClassRef, "setApplicationUIContext", "(Landroid/content/Context;)V"); Android.Runtime.JNIEnv.CallStaticVoidMethod(javaClassRef, javaMethodRef, new Android.Runtime.JValue(context)); }#endif`

2. You have to add Xamarin.Kotlin.Stdlib "https://www.nuget.org/packages/Xamarin.Kotlin.StdLib" in order to build VidyoClient for Android now. Without Kotlin Plugin you'll run into a runtime exception. Kotlin is a modern lang suggested by Google and preferred lang for Android development so we are taking small integrations steps.

**Comment by jmosbech** [comment]
Thank you @tmelko-vidyo. 

Unfortunately our build process automatically pulls the Vidyo SDK directly from your CDN, so it's not so easy for us to manually patch it.

Do you have any idea of the ETA of 22.x?

**Comment by tmelko-vidyo** [comment]
Resolved with 22.1 Lib Upgrade
